title: Deshrit Baral
email: deshritbaral@gmail.com
baseurl: ""
url: "https://deshritbaral.com.np"
linkedin_username: deshrit
github_username:  deshrit
youtube_username: "@deshrit"

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - home.md
  - blog.md

google_analytics:
  id: G-CMDTH72TR2

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
